version: "3.1"

services:
  rinha_backend_app:
    container_name: rinha_backend_app
    build: .
    ports:
      - '127.0.0.1:5000:5000'
    volumes:
        - .:/rinha-de-backend-2023-q3-python-flask
    env_file:
        - .env.example

  rinha_backend_redis_db:
    container_name: rinha_backend_redis_db
    image: redis
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - '127.0.0.1:6379:6379'

  rinha_backend_postgres_db:
    container_name: rinha_backend_postgres_db
    image: postgres:15
    restart: always
    volumes:
      - rinha_backend_postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"

  rinha_backend_ngnix_server:
    container_name: rinha_backend_ngnix_server
    image: nginx
    volumes:
      - ./nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=rinha_backend_app:5000
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    depends_on:
      - rinha_backend_app

volumes:
  rinha_backend_postgres_volume:
    driver: local
