version: "3.1"

services:
  rinha_backend_app:
    container_name: rinha_backend_app
    build: .
    ports:
      - '127.0.0.1:5000:5000'
    volumes:
        - .:/home/rinha_backend/rinha-de-backend-2023-q3-python-flask
    env_file:
        - .env.example
    deploy:
        resources:
          limits:
            cpus: '0.3'
            memory: '1.0GB'
    networks:
        - rinha_backend_network_default

  rinha_backend_redis_db:
    container_name: rinha_backend_redis_db
    image: redis
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - '127.0.0.1:${REDIS_PORT}:6379'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'
    networks:
      - rinha_backend_network_default

  rinha_backend_postgres_db:
    container_name: rinha_backend_postgres_db
    image: postgres:15
    restart: always
    volumes:
      - rinha_backend_postgres_volume:/var/lib/postgresql/data
    command: postgres -c shared_buffers=384MB -c max_connections=100 -c log_min_messages=FATAL
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: '1GB'
    healthcheck:
        test: ["CMD-SHELL", "pg_isready --dbname=${POSTGRES_DB} --username=${POSTGRES_USER}"]
        interval: 2s
        timeout: 2s
        retries: 30
    networks:
      - rinha_backend_network_default

  rinha_backend_ngnix_server:
    container_name: rinha_backend_ngnix_server
    image: nginx
    volumes:
      - ./nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=rinha_backend_app:5000
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    depends_on:
      - rinha_backend_app
    networks:
      - rinha_backend_network_default
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '0.5GB'

volumes:
  rinha_backend_postgres_volume:
    driver: local

networks:
  rinha_backend_network_default:
    driver: bridge
