version: "3.1"

services:
  rinha_backend_app_instance_a:
    container_name: rinha_backend_app_instance_a
    build:
      context: .
      dockerfile: DockerfileInstanceA
    ports:
      - '127.0.0.1:5000:5000'
    volumes:
        - .:/home/rinha_backend/rinha-de-backend-2023-q3-python-flask
    deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: '0.5GB'
    networks:
        - rinha_backend_network_default
    environment:
      - PATH=/home/rinha_backend/rinha-de-backend-2023-q3-python-flask/venv/bin:$PATH
    env_file:
      - .env.example

  rinha_backend_app_instance_b:
    container_name: rinha_backend_app_instance_b
    build:
      context: .
      dockerfile: DockerfileInstanceB
    ports:
      - '127.0.0.1:5001:5000'
    volumes:
        - .:/home/rinha_backend/rinha-de-backend-2023-q3-python-flask
    deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: '0.5GB'
    networks:
        - rinha_backend_network_default
    environment:
      - PATH=/home/rinha_backend/rinha-de-backend-2023-q3-python-flask/venv/bin:$PATH
    env_file:
      - .env.example

  rinha_backend_redis_db:
    container_name: rinha_backend_redis_db
    image: redis
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - '127.0.0.1:${REDIS_PORT}:6379'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    networks:
      - rinha_backend_network_default

  rinha_backend_postgres_db:
    container_name: rinha_backend_postgres_db
    image: postgres:15
    restart: always
    command: postgres -c shared_buffers=384MB -c max_connections=100 -c log_min_messages=FATAL
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '1GB'
    healthcheck:
        test: ["CMD-SHELL", "pg_isready --dbname=${POSTGRES_DB} --username=${POSTGRES_USER}"]
        interval: 2s
        timeout: 2s
        retries: 30
    networks:
      - rinha_backend_network_default

  rinha_backend_ngnix_server:
    container_name: rinha_backend_ngnix_server
    restart: always
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - rinha_backend_network_default
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

networks:
  rinha_backend_network_default:
    driver: bridge
