"""c7904170-5a74-11ee-b199-0242c0a8a005

Revision ID: adb0590fc0b3
Revises: 
Create Date: 2023-09-23 21:53:33.185667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb0590fc0b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('apelido', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('stack', sa.ARRAY(sa.String(length=32)), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apelido')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoa')
    # ### end Alembic commands ###
